# @package experiment.config

do_train: true
train_env_interface_args:
  object_names:
  - 001_cube
  - 006_disk
  - 002_cube_tbp
  - 004_cube_numenta
  - 007_disk_tbp
  - 009_disk_numenta
  - 011_cylinder
  - 016_sphere
  - 023_mug
  - 012_cylinder_tbp_horz
  - 014_cylinder_numenta_horz
  - 017_sphere_tbp
  - 019_sphere_numenta
  - 024_mug_tbp_horz
  - 026_mug_numenta_horz
  - 013_cylinder_tbp_vert
  - 015_cylinder_numenta_vert
  - 025_mug_tbp_vert
  - 027_mug_numenta_vert
  - 101_cube_sq_ci_sq_ci_st_ci
  - 102_cylinder_tr_ci_he_ci_he_st
  - 103_disk_st_sq_sq_st_ci_tr
  - 104_mug_tr_ci_st_tr_tr_st
  - 105_sphere_st_he_sq_tr_sq_sq
  - 106_cube_st_tr_sq_he_ci_tr
  - 107_cylinder_he_ci_st_ci_st_st
  - 108_disk_sq_tr_st_ci_ci_ci
  - 109_mug_he_st_ci_sq_st_sq
  - 110_sphere_sq_tr_sq_he_st_sq
  - 111_cube_st_st_st_he_sq_ci
  - 112_cylinder_tr_he_sq_tr_sq_ci
  - 113_disk_he_tr_sq_ci_tr_he
  - 114_mug_tr_st_st_st_sq_ci
  - 115_sphere_sq_sq_tr_st_ci_ci
  - 116_cube_he_tr_st_st_tr_sq
  - 117_cylinder_ci_sq_st_tr_st_ci
  - 118_disk_sq_tr_ci_sq_st_tr
  - 119_mug_he_tr_he_sq_sq_tr
  - 120_sphere_he_st_sq_st_sq_sq
  - 121_cube_he_he_st_tr_st_sq
  - 122_cylinder_ci_st_st_ci_st_ci
  - 123_disk_he_ci_st_he_ci_ci
  - 124_mug_sq_sq_he_ci_he_sq
  - 125_sphere_ci_st_st_tr_he_st
  - 126_cube_sq_tr_sq_ci_sq_st
  - 127_cylinder_he_st_he_st_he_st
  - 128_disk_ci_he_ci_st_he_ci
  - 129_mug_he_sq_sq_ci_ci_sq
  - 130_sphere_tr_he_he_tr_ci_tr
  - 131_cube_ci_ci_sq_tr_sq_ci
  - 132_cylinder_st_ci_sq_he_st_he
  - 133_disk_he_sq_ci_tr_he_he
  - 134_mug_tr_sq_tr_ci_tr_ci
  - 135_sphere_st_ci_ci_st_ci_tr
  - 136_cube_he_st_he_ci_tr_sq
  - 137_cylinder_he_sq_tr_tr_sq_tr
  - 138_disk_ci_he_ci_ci_st_he
  - 139_mug_ci_ci_ci_sq_he_st
  - 140_sphere_st_st_tr_sq_st_he
  - 141_cube_sq_he_tr_tr_sq_st
  - 142_cylinder_tr_tr_he_tr_tr_tr
  - 143_disk_he_tr_sq_tr_sq_tr
  - 144_mug_ci_he_he_tr_tr_st
  - 145_sphere_sq_he_st_sq_he_st
  - 146_cube_tr_he_he_st_tr_he
  - 147_cylinder_ci_sq_st_st_st_he
  - 148_disk_sq_sq_tr_sq_tr_he
  - 149_mug_st_st_sq_sq_he_ci
  - 150_sphere_ci_tr_tr_tr_st_st
  - 151_cube_st_sq_tr_ci_st_ci
  - 152_cylinder_ci_st_st_st_ci_st
  - 153_disk_tr_st_sq_he_ci_ci
  - 154_mug_sq_ci_tr_st_he_tr
  - 155_sphere_he_st_he_sq_st_st
  - 156_cube_st_sq_ci_tr_tr_tr
  - 157_cylinder_he_tr_tr_he_sq_sq
  - 158_disk_he_he_he_he_tr_sq
  - 159_mug_tr_tr_he_he_ci_sq
  - 160_sphere_ci_ci_ci_he_sq_he
  - 161_cube_ci_sq_he_he_st_he
  - 162_cylinder_he_tr_he_he_he_tr
  - 163_disk_ci_ci_sq_ci_he_st
  - 164_mug_he_he_sq_tr_tr_sq
  - 165_sphere_sq_st_tr_ci_st_tr
  - 166_cube_st_sq_st_sq_st_ci
  - 167_cylinder_sq_st_st_st_he_sq
  - 168_disk_he_st_sq_st_sq_he
  - 169_mug_tr_he_sq_he_tr_he
  - 170_sphere_he_sq_he_sq_ci_he
  - 171_cube_sq_st_tr_sq_ci_st
  - 172_cylinder_ci_tr_st_tr_st_sq
  - 173_disk_he_sq_he_he_tr_ci
  - 174_mug_tr_tr_he_he_sq_st
  - 175_sphere_he_ci_sq_he_he_sq
  - 176_cube_ci_ci_sq_st_tr_he
  - 177_cylinder_tr_sq_tr_sq_st_sq
  - 178_disk_st_sq_he_he_ci_st
  - 179_mug_sq_he_he_tr_st_he
  - 180_sphere_tr_he_ci_he_st_he
  - 181_cube_he_sq_st_st_tr_he
  - 182_cylinder_tr_st_ci_ci_st_ci
  - 183_disk_ci_he_tr_sq_ci_st
  - 184_mug_ci_ci_st_st_ci_sq
  - 185_sphere_ci_sq_he_tr_ci_sq
  - 186_cube_ci_sq_st_tr_he_tr
  - 187_cylinder_ci_st_st_ci_he_tr
  - 188_disk_tr_ci_tr_sq_he_sq
  - 189_mug_sq_ci_st_he_tr_he
  - 190_sphere_st_he_ci_ci_he_sq
  - 191_cube_tr_ci_tr_tr_tr_sq
  - 192_cylinder_ci_he_sq_tr_he_ci
  - 193_disk_sq_ci_st_ci_tr_st
  - 194_mug_he_sq_sq_he_sq_tr
  - 195_sphere_ci_st_tr_st_he_he
  - 196_cube_ci_tr_he_st_he_st
  - 197_cylinder_ci_st_tr_ci_he_st
  - 198_disk_sq_tr_tr_st_tr_he
  - 199_mug_st_tr_st_sq_sq_tr
  - 200_sphere_sq_ci_he_st_st_ci
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
    rotations: ${constants.rotations_cube_faces}
train_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
