# @package experiment.config.logging

python_log_level: WARNING
python_log_to_file: true
python_log_to_stderr: true
output_dir: ${path.expanduser:${oc.env:MONTY_LOGS}/projects/monty_runs/}

monty_data_logger:
  _target_: tbp.monty.frameworks.loggers.graph_matching_loggers.BasicGraphMatchingLogger
  handlers: []
