# @package experiment.config.logging

python_log_level: WARNING
python_log_to_file: true
python_log_to_stderr: true
output_dir: ${path.expanduser:${oc.env:MONTY_MODELS}/my_trained_models}

monty_data_logger:
  _target_: tbp.monty.frameworks.loggers.exp_logger.BaseMontyLogger
  handlers: []
