# @package experiment.config

match_criterion:
  _target_: tbp.monty.experiment.match_criteria.AnyLMsMatch
  count: 1
recognition_policy:
  _target_: tbp.monty.experiment.recognition_policy.AnyPolicy
  policies:
  - _target_: tbp.monty.experiment.recognition_policy.StepLimit
    min_train_steps: 3
    num_exploring_steps: 20
    max_train_steps: 20
    max_eval_steps: 20
  - _target_: tbp.monty.experiment.recognition_policy.MaxTotalSteps
    max_total_steps: 6000
  - _target_: tbp.monty.experiment.recognition_policy.MontyIsDone
