# @package experiment.config

match_criterion:
  _target_: tbp.monty.experiment.match_criteria.NamedLMsMatch
  ids:
    - learning_module_2
recognition_policy:
  _target_: tbp.monty.experiment.recognition_policy.ObjectRecognition
  max_train_steps: 1000
  max_eval_steps: 100
  max_total_steps: 6000
