# @package experiment.config

match_criterion:
  _target_: tbp.monty.experiment.match_criteria.AnyLMsMatch
  count: 1
recognition_policy:
  _target_: tbp.monty.experiment.recognition_policy.ObjectRecognition
  max_train_steps: 50
  max_eval_steps: 50
  max_total_steps: 200
