# @package experiment.config

match_criterion:
  _target_: tbp.monty.experiment.match_criteria.AnyLMsMatch
  count: 1
recognition_policy:
  _target_: tbp.monty.experiment.recognition_policy.NaiveScan
  fixed_amount: 10
  max_total_steps: 6000
